version: '3.8'

services:
  api:
    build: .
    container_name: todoapi
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: todoapi_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapi
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
